#!/usr/bin/env python3
"""
scan_kinds.py — Propose paragraph `kind` assignments for a book.

Walks chapter-N.json files and surfaces two non-body paragraph kinds:

  - title         A heading-like paragraph that should render as <h3> in
                  the reader and (in the audio play) get a longer
                  lead-pause + the AudioplayNarrator voice when that role
                  ships. Example in TBWTT: "The atomic bombs",
                  "The Tower of Babel", "L'éducation chimique".

  - continuation  A paragraph that completes a quotation split across two
                  paragraphs in the source. The reader should tighten the
                  margin against the previous paragraph; the audio play
                  should TTS-concat with no inter-paragraph silence.
                  Example: TBWTT 2:69 "«By these were the nations divided
                  in the earth after the" → 2:70 "Flood.» (Genesis, X-32)".

The script does NOT mutate the chapter files. It writes a proposal JSON
the editor reviews + adjusts before any apply step.

Usage:
    scripts/scan_kinds.py <book-slug>            # writes _kinds-proposal.json
    scripts/scan_kinds.py the-book-which-tells-the-truth
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

OPEN_QUOTES = "«“„"
CLOSE_QUOTES = "»”"
TERMINAL = ".!?……"


def is_title_candidate(p: dict) -> bool:
    text = p.get("text", "").strip()
    if not text:
        return False
    if p.get("speaker") != "Narrator":
        return False
    if len(text) > 60:
        return False
    if text[0] in OPEN_QUOTES + "\"'(":
        return False
    if text[-1] in TERMINAL:
        return False
    if text.endswith(","):
        return False
    return True


def quote_balance(text: str) -> int:
    """Positive = more opens than closes (unclosed quotation)."""
    opens = sum(text.count(q) for q in OPEN_QUOTES)
    closes = sum(text.count(q) for q in CLOSE_QUOTES)
    return opens - closes


def is_continuation_candidate(prev: dict | None, cur: dict) -> bool:
    if prev is None:
        return False
    if prev.get("speaker") != cur.get("speaker"):
        return False
    prev_text = prev.get("text", "").strip()
    cur_text = cur.get("text", "").strip()
    if not prev_text or not cur_text:
        return False
    # Previous paragraph must have an unclosed quotation.
    if quote_balance(prev_text) <= 0:
        return False
    # Current paragraph must contain a closing quote (completing the
    # quotation) — and ideally near the start.
    head = cur_text[:50]
    if not any(q in head for q in CLOSE_QUOTES):
        return False
    return True


def scan_book(book_dir: Path) -> dict:
    meta = json.loads((book_dir / "_meta.json").read_text())
    proposal = {
        "_meta": {
            "book": meta["slug"],
            "scanned_chapters": meta.get("chapterCount", 0),
            "note": (
                "Auto-generated by scripts/scan_kinds.py. Each candidate "
                "should be reviewed: confirm by leaving kind set, reject "
                "by deleting the entry or setting kind to null. After "
                "review, run scripts/apply_kinds.py to write the kinds "
                "into chapter-N.json."
            ),
        },
        "candidates": [],
    }

    for entry in meta["chapterFiles"]:
        chapter_path = book_dir / entry["file"]
        chapter = json.loads(chapter_path.read_text())
        paras = chapter["paragraphs"]
        for i, p in enumerate(paras):
            prev = paras[i - 1] if i > 0 else None
            kind = None
            if is_title_candidate(p):
                kind = "title"
            elif is_continuation_candidate(prev, p):
                kind = "continuation"
            if kind is None:
                continue
            proposal["candidates"].append({
                "chapter": entry["n"],
                "n": p["n"],
                "refId": p["refId"],
                "speaker": p["speaker"],
                "kind": kind,
                "text_fr": p.get("text", ""),
                "text_en": p.get("i18n", {}).get("en", ""),
            })

    return proposal


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    book_slug = argv[1]
    book_dir = Path(book_slug)
    if not book_dir.is_dir():
        print(f"error: {book_dir} is not a directory", file=sys.stderr)
        return 1
    proposal = scan_book(book_dir)
    out_path = book_dir / "_kinds-proposal.json"
    out_path.write_text(json.dumps(proposal, indent=2, ensure_ascii=False))
    n_title = sum(1 for c in proposal["candidates"] if c["kind"] == "title")
    n_cont = sum(1 for c in proposal["candidates"] if c["kind"] == "continuation")
    print(
        f"wrote {out_path}  ({n_title} title, {n_cont} continuation, "
        f"{len(proposal['candidates'])} total)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
